use hrms;
alter table state_master modify column state_name varchar(30);
alter table city_master modify column city_name varchar(30);
insert into state_master (state_name) values ("Delhi"),
    ("Goa"),
    ("Gujarat"),
    ("Rajstan"),
    ("Madhay Pradesh"),
    ("Jammu and Kashmir"),
    ("Maharastra"),
    ("Karnataka"),
    ("Kerala");
    
    insert into city_master(fk_state_id,city_name) values 
(1,'Mehrauli'),
(1,'Siri'),
(1,'Tughlakabad'),
(1,'Firozabad'),
(1,'Shergarh'),
(1,'Shahjehabanad'),
(1,'NewDelhi');
insert into city_master(fk_state_id,city_name) values
(2,'Margao'),	
(2,'Mormugao'),	
(2,'Panaji'),
(3,'ahmedabad'),
(3,'rajkot'),
(3,'bhavnagar'),
(3,'surat'),
(3,'morbi'),
(3,'surendranagar'),
(3,'junagadh'),

(6,'agra'),
(6,'banda'),
(6,'prayagraj'),
(6,'gorakhpur'),
(6,'kanpur'),
(6,'mirzapur'),
(6,'varansi'),
(6,'amigadh'),
(5,'bhopal'),
(5,'ghuna'),
(5,'betul'),
(5,'harda'),
(5,'jabalpur'),
(5,'mandala'),
(5,'sagar'),
(7,'mumbai'),
(7,'lonavala'),
(7,'bordi'),
(7,'nagpur'),
(7,'solapur'),
(7,'nasik'),
(7,'pune'),
(4,'jaipur'),
(4,'pali'),
(4,'udaipur'),
(4,'barmer'),
(4,'ajmer'),
(4,'bikaner'),
(4,'mountabu'),

(8,'Bangalore'),	
(8,'Hubli'),(8,'Mysore'),	(8,'Kalaburagi'),(9,'Thiruvanantam'),	(9,'Kozhikode'),(9,'Kochi');
